### ISSUE TITLE
Error installing dependencies on Windows

### ISSUE THREAD

**Issue by ogranada** [weirongxu/coc-helper#4]
# Environment information:

OS: Windows 10 Pro 64bits, x64
Node: v15.5.1
NPM: v7.3.0

# Issue information

When the package is cloned and the command `npm install --ignore-scripts --no-lockfile --production` is executed the dependency `"@types/node": "^14.14.16"` cause a install failure.

![image](https://user-images.githubusercontent.com/1445677/104127045-e70db100-532d-11eb-9d40-41130afeade1.png)

**Comment by weirongxu** [comment]
Maybe you need to add the `--legacy-peer-deps` argument to your npm command

https://github.com/neoclide/coc.nvim/commit/789e871d868d71dd97d59e11cc395c7fb089951a

**Comment by ogranada** [comment]
The problem is that CoC plug-in system don't add that flag when a plug-in is installed. Therefore, the plug-in can't be installed on Windows by the CoC plug-in system.

**Comment by weirongxu** [comment]
OK, the latest coc.nvim already added this argument.
